# Generated by Django 5.0.6 on 2024-06-17 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('username', models.CharField(max_length=260)),
                ('password', models.CharField(max_length=260)),
                ('api_url', models.URLField(error_messages={'unique': 'This API URL has already been registered.'}, max_length=300, unique=True)),
                ('expiration', models.DateField(default=datetime.datetime(2024, 12, 17, 14, 1, 45, 844783))),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
