# Generated by Django 5.0.6 on 2024-06-17 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='expiration',
            field=models.DateField(default=datetime.datetime(2024, 12, 17, 14, 19, 11, 451207)),
        ),
    ]
